{"name": "test_for_users_duplicate", "status": "broken", "statusDetails": {"message": "TypeError: list indices must be integers or slices, not str", "trace": "@allure.feature(\"Create already exist User\")\n    @allure.story(\"Authorized user can not add users information\")\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_for_users_duplicate():\n    \n        response = helper.post_request(url=POST_URL,\n                                              body={'name':'Abhishek Yadav', 'gender':'Male',\n                                                    'email':'yabhishek@outlook.com', 'status':'Active'})\n    \n        check.response_has_status_code(response, 200)\n        check.response_has_field_with_value(response, 'code', 422)\n        check.response_has_fields(\n            response,\n            'data'\n        )\n>       check.response_has_field_value(response, \"field\", 'email')\n\nresponse   = <Response [200]>\n\ntest.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [200]>, field = 'field', expected_value = 'email'\n\n    def response_has_field_value(response, field, expected_value):\n        with allure.step(f'Check response has one of {expected_value} expected value'):\n            res = json.loads(response.text)\n            actual_value = res['data']\n>           assert actual_value[field][0] in expected_value, f'''\n                Expected value: {expected_value}\n                Actual value: {actual_value}\n            '''\nE           TypeError: list indices must be integers or slices, not str\n\nactual_value = [{'field': 'email', 'message': 'has already been taken'}]\nexpected_value = 'email'\nfield      = 'field'\nres        = {'code': 422,\n 'data': [{'field': 'email', 'message': 'has already been taken'}],\n 'meta': None}\nresponse   = <Response [200]>\n\n..\\testlib\\check.py:28: TypeError"}, "steps": [{"name": "Send POST request by authorized user to url:\n https://gorest.co.in/public-api/users", "status": "passed", "attachments": [{"source": "36fcdcf1-e60c-4e27-a01d-e7e655bbed1d-attachment.attach"}, {"source": "a2bdd5ff-0a3f-4c68-8b38-9b95dc83b941-attachment.attach"}], "start": 1620598530634, "stop": 1620598531155}, {"name": "Check response has one of (200,) status code", "status": "passed", "start": 1620598531155, "stop": 1620598531155}, {"name": "Check response jsondata have code field with 422 value", "status": "passed", "start": 1620598531155, "stop": 1620598531155}, {"name": "Check response jsondata have all of ('data',) fields", "status": "passed", "start": 1620598531155, "stop": 1620598531155}, {"name": "Check response has one of email expected value", "status": "broken", "statusDetails": {"message": "TypeError: list indices must be integers or slices, not str\n", "trace": "  File \"D:\\MyWorkspace\\api_tests_python_allure\\testlib\\check.py\", line 28, in response_has_field_value\n    assert actual_value[field][0] in expected_value, f'''\n"}, "start": 1620598531155, "stop": 1620598531155}], "start": 1620598530634, "stop": 1620598531156, "uuid": "537ad257-ab98-4c4e-b861-248bc28936f5", "historyId": "90db21108ff4a0e23ca7eeedefc30d6d", "testCaseId": "2b61faf00e535626e31545461e44eb04", "fullName": "tests.test#test_for_users_duplicate", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Create already exist User"}, {"name": "story", "value": "Authorized user can not add users information"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "abhishekkyd"}, {"name": "thread", "value": "21612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test"}]}