{"name": "test_for_users_add", "status": "failed", "statusDetails": {"message": "AssertionError: \n            Expected 'code' field value don't equal to:\n            201\n            Actual 'code' field value:\n            422", "trace": "@allure.feature(\"Create a User\")\n    @allure.story(\"Authorized user can add users information\")\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_for_users_add():\n    \n        response = helper.post_request(url=POST_URL,\n                                              body={'name':'Abhishek Yadav', 'gender':'Male',\n                                                    'email':'yabhishek2@outlook.com', 'status':'Active'})\n    \n        check.response_has_status_code(response, 200)\n>       check.response_has_field_with_value(response, 'code', 201)\n\nresponse   = <Response [200]>\n\ntest.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [200]>, field = 'code', value = 201\n\n    def response_has_field_with_value(response, field, value):\n        with allure.step(f'Check response jsondata have {field} field with {value} value'):\n            actual_field_value = response.json().get(field)\n            assert actual_field_value, f'Response does not have expected {field} field'\n            assert value == actual_field_value, f'''\n                Expected '{field}' field value don't equal to:\n                {value}\n                Actual '{field}' field value:\n                {actual_field_value}\n>           '''\nE           AssertionError: \nE                       Expected 'code' field value don't equal to:\nE                       201\nE                       Actual 'code' field value:\nE                       422\n\nactual_field_value = 422\nfield      = 'code'\nresponse   = <Response [200]>\nvalue      = 201\n\n..\\testlib\\check.py:72: AssertionError"}, "steps": [{"name": "Send POST request by authorized user to url:\n https://gorest.co.in/public-api/users", "status": "passed", "attachments": [{"source": "16c4393a-2bc9-4269-9af7-235acdb52a28-attachment.attach"}, {"source": "51c9247c-6a0b-42ee-b77d-c5fd79d575c1-attachment.attach"}], "start": 1620599373751, "stop": 1620599374159}, {"name": "Check response has one of (200,) status code", "status": "passed", "start": 1620599374159, "stop": 1620599374160}, {"name": "Check response jsondata have code field with 201 value", "status": "failed", "statusDetails": {"message": "AssertionError: \n            Expected 'code' field value don't equal to:\n            201\n            Actual 'code' field value:\n            422\n        \n", "trace": "  File \"D:\\MyWorkspace\\api_tests_python_allure\\testlib\\check.py\", line 72, in response_has_field_with_value\n    '''\n"}, "start": 1620599374160, "stop": 1620599374160}], "start": 1620599373751, "stop": 1620599374160, "uuid": "4eb311d5-3913-41ef-a893-5f2445c21391", "historyId": "8a23fe126d735ad0c7d9aa3a5d83d99a", "testCaseId": "ab0c4275d0185bad95fbe3a524f162af", "fullName": "tests.test#test_for_users_add", "labels": [{"name": "feature", "value": "Create a User"}, {"name": "severity", "value": "blocker"}, {"name": "story", "value": "Authorized user can add users information"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "abhishekkyd"}, {"name": "thread", "value": "3272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test"}]}